version: "3.7"
services:
  gatsby-my-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatsby-my-site
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    # command: sh -c "cd my-gatsby-site && gatsby develop --host=0.0.0.0"
    environment:
      - NODE_ENV=development
