version: '3'

services:
  next-app:
    build: .
    container_name: next-blog
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./next-app:/app
    stdin_open: true
    tty: true